Update GitHub Actions OIDC for multiple repos
hashicorp/terraform#31133

The GitHub Actions OIDC (OpenID Connect) example works well for
provisioning credentials for a single repo, but not for multiple repos.

To configure credentials for multiple repos, a downstream configuration
might iterate over a `module` block with `for_each`.

```hcl
variable "github_repos" {
  type = map(object({
    org  = string
    repo = string
  }))
  default = {
    my-github-org-repo0 = {
      org  = "my-github-org"
      repo = "repo0"
    },
    my-github-org-repo1 = {
      org  = "my-github-org"
      repo = "repo1"
    }
  }
}
```

```hcl
module "github_actions_oidc" {
  for_each                 = var.github_repos
  source                   = "app.terraform.io/<YOUR_TERRAFORM_CLOUD_ORG>/github-actions-oidc/aws"
  github_org               = each.value.org
  github_repo              = each.value.repo
}
```

However, the following error would be seen on the second iteration:

```log
Error: error creating IAM OIDC Provider:
EntityAlreadyExists:
Provider with url https://token.actions.githubusercontent.com already exists.
status code: 409
```

The error occurs because there should only be one OIDC provider per AWS
account (the ARN will be
`arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/token.actions.githubusercontent.com`).

The module therefore needs a way to ensure it only tries to instantiate
one OIDC provider per AWS account.

This commit will update the example so that, rather than using
`for_each` on the `module` block (multiple `module` blocks, with one
repo per block), there would be one `module` block, with multiple repos
passed in to the block with an input variable.